Repository jenkins-x-plugins/jx-scm, pull requests merged in 2022-09, with the labels that each got.

#27 chore: adding dependabot config
  .github/dependabot.yml
Labels: approved, size/XS

#25 feat: add supply chain security
  .gitignore
  .goreleaser.yml
  .lighthouse/jenkins-x/release.yaml
Labels: approved, size/M, ok-to-test

#33 refactor: upgrade go version to 1.18.6
  go.mod
  go.sum
Labels: approved, size/XL
